// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxdcirmqvdsmlxmvaxiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4ZGNpcm1xdmRzbWx4bXZheGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODg3MDYsImV4cCI6MjA2MTM2NDcwNn0.fD2_gtrb1qylgYBNsevaebsFxYT0SHuXue4Wlv_dZfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);